apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deploy
  namespace: dai-simplon
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: daidock/streamlit-clients:latest
          env:
            - name: API_URL
              value: http://api-svc:8000
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-svc
spec:
  selector:
    app: streamlit
  ports:
    - port: 80
      targetPort: 8501
  type: ClusterIP
