apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dai-simplon
type: Opaque
stringData:
  mysql-root-password: root
  mysql-user: user
  mysql-password: password
  mysql-database: clients